Repository prgrms-web-devcourse-final-project/WEB1_2_Inte11i9ence_FE, pull requests merged in 2024-11, with the labels that each got.

#3 Docs: PR, Issue 템플릿 이모지 출력 오류 수정
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature-request-template.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  tailwind.config.js
Labels: ⚙️ setting

#6 네비게이션 마크업 + 기능
  index.html
  src/App.css
  src/App.tsx
  src/assets/png/default-profile-1.png
  src/assets/png/default-profile-2.png
  src/assets/png/default-profile.png
  src/assets/svg/Airplain.svg
  src/assets/svg/Announcement.svg
  src/assets/svg/Comment.svg
  src/assets/svg/Like.svg
  src/assets/svg/LiveNotiIcon.svg
  src/assets/svg/NextButton.svg
  src/assets/svg/Note.svg
  src/assets/svg/NotiIcon.svg
  src/main.tsx
  src/pages/Navigater/MyDropdown.tsx
  src/pages/Navigater/Navigater.tsx
  src/pages/Navigater/NotiDropdown.tsx
  src/pages/Navigater/mockdata.ts
  src/pages/SchedulePage/SchedulePage.tsx
  src/utils/formatTime.ts
  tailwind.config.js
Labels: ✨ feature

#11 7 feat 마이/다른 유저 페이지 조회 마크업 + 기능
  src/App.tsx
  src/assets/svg/Comment.svg
  src/assets/svg/Like.svg
  src/assets/svg/Location.svg
  src/assets/svg/Toggle.svg
  src/components/DropdownSelector.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/MypageGather.tsx
  src/pages/Mypage/MypagePlaces.tsx
  src/pages/Mypage/MypagePostList.tsx
  src/pages/Mypage/mockdata.ts
  src/pages/Navigater/MyDropdown.tsx
  src/pages/Navigater/NotiDropdown.tsx
  tailwind.config.js
Labels: ✨ feature

#16 로그인창 구현
  src/App.css
  src/App.tsx
  src/assets/png/AirPlane.png
  src/assets/png/Google.png
  src/assets/png/Naver.png
  src/assets/png/Profiles.png
  src/components/LoginPage.tsx
  src/components/MainLogin.tsx
  src/components/Profile.tsx
Labels: ✨ feature

#27 19 feat로그인창 모달 마크업
  src/App.tsx
  src/assets/svg/Pin.svg
  src/components/MainLogin.tsx
  src/pages/Navigater/Navigater.tsx
  src/pages/PhotoPage/PhotoAdd.tsx
  src/pages/PhotoPage/PhotoDetail.tsx
  src/pages/PhotoPage/PhotoPage.tsx
  src/pages/PhotoPage/mockdata.ts
  src/pages/PhotoPage/vote.tsx
  src/pages/SchedulePage/ScheduleAdd.tsx
  src/pages/SchedulePage/SchedulePage.tsx
Labels: ✨ feature

#28 feat:로그인창 모달 마크업
  src/components/MainLogin.tsx
  src/pages/Navigater/Navigater.tsx
Labels: ✨ feature

#30 채팅 페이지 마크업
  src/App.tsx
  src/pages/ChatPage/ChatBox.tsx
  src/pages/ChatPage/ChatPage.tsx
  src/pages/Mypage/MypagePlaces.tsx
Labels: 🎨 style
